display: true
display_down_scale: 5
width: 3072
height: 2048
binning: 2
gain: -1
serial_num: 33120263
framerate: 30
emperical_framerate: 15
ExposureTime_us: -1

detect: true
min_area: 100
max_area: 8000

track: true
port: /dev/ttyACM0
center_window_px: 200
pan_limit: 50
tilt_limit: 50
tilt_flip: -1
pan_flip: 1
